[package]
name = "lsat-middleware-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
hex = "0.4.3"
lightning = "0.0.115"
macaroon = "0.3.0"
rand = "0.8.5"
rocket = { version = "0.5.0-rc.3", features = ["json"] }
serde = "1.0.152"
