name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose -f docker-compose-lnd-test.yml up --build -d

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Create env file
        run: |
          touch .env
          echo ROOT_KEY=${{ secrets.ROOT_KEY }} >> .env
          cat .env

      - name: Run tests for LNURL
        run: cargo test --verbose
        env: 
          LN_CLIENT_TYPE: LNURL
          LNURL_ADDRESS: ${{ secrets.LNURL_ADDRESS }}

      - name: Extract Macaroon and Cert Paths
        run: |
          # Define the container name
          CONTAINER_NAME="lndnode"

          # Define paths to the macaroon and certificate in the container
          MACAROON_PATH="/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon"
          CERT_PATH="/root/.lnd/tls.cert"

          # Copy macaroon from the container to the workspace
          docker cp ${CONTAINER_NAME}:${MACAROON_PATH} ./admin.macaroon

          # Check if the macaroon was copied successfully
          if [ -f "./admin.macaroon" ]; then
            echo "Extracted MACAROON_PATH: ./admin.macaroon"
            echo "MACAROON_PATH=./admin.macaroon" >> $GITHUB_ENV
          else
            echo "Error: Macaroon file not found after copying."
            exit 1
          fi

          # Copy certificate from the container to the workspace
          docker cp ${CONTAINER_NAME}:${CERT_PATH} ./tls.cert

          # Check if the certificate was copied successfully
          if [ -f "./tls.cert" ]; then
            echo "Extracted CERT_PATH: ./tls.cert"
            echo "CERT_PATH=./tls.cert" >> $GITHUB_ENV
          else
            echo "Error: Certificate file not found after copying."
            exit 1
          fi

      - name: Run tests for LND
        run: cargo test --verbose
        env:
          LN_CLIENT_TYPE: LND
          LND_ADDRESS: lsat-middleware-rust-bitcoind-1:10009
          MACAROON_FILE_PATH: ${{ env.MACAROON_PATH }}
          CERT_FILE_PATH: ${{ env.CERT_PATH }}
