name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      bitcoind:
        image: lncm/bitcoind:v22.0@sha256:37a1adb29b3abc9f972f0d981f45e41e5fca2e22816a023faa9fdc0084aa4507
        container_name: mercurylayer-bitcoind-1
        user: root
        command: -regtest -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcauth=user:63cf03615adebaa9356591f95b07ec7b$$920588e53f94798bda636acac1b6a77e10e3ee7fe57e414d62f3ee9e580cd27a -fallbackfee=0.0001 -zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubrawtx=tcp://0.0.0.0:28333
        ports:
          - "18443:18443"
          - "28332:28332"
          - "28333:28333"
        volumes:
          - bitcoin_data:/root/.bitcoin

      alice:
        image: lightninglabs/lndinit:v0.1.21-beta-lnd-v0.18.0-beta
        container_name: mercurylayer-alice-1
        user: root
        hostname: lnd
        entrypoint: 
          - sh
          - -c
          - |
            if [[ ! -f /data/seed.txt ]]; then
              lndinit gen-seed > /data/seed.txt
            fi
            if [[ ! -f /data/walletpassword.txt ]]; then
              lndinit gen-password > /data/walletpassword.txt
            fi
            lndinit -v init-wallet \
              --secret-source=file \
              --file.seed=/data/seed.txt \
              --file.wallet-password=/data/walletpassword.txt \
              --init-file.output-wallet-dir=/root/.lnd/data/chain/bitcoin/regtest \
              --init-file.validate-password
            mkdir -p /data/.lnd
            if [ ! -f "/data/.lnd/umbrel-lnd.conf" ]; then
              touch "/data/.lnd/umbrel-lnd.conf"
            fi
            lnd --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.rpcuser=user --bitcoind.rpcpass=pass --bitcoind.zmqpubrawblock=tcp://bitcoind:28332 --bitcoind.zmqpubrawtx=tcp://bitcoind:28333 --configfile=/data/.lnd/umbrel-lnd.conf --wallet-unlock-password-file=/data/walletpassword.txt --wallet-unlock-allow-create
        ports:
          - "9735:9735"
          - "10009:10009"
          - "8080:8080"
        volumes:
          - alice-data:/data/.lnd
        restart: unless-stopped
        environment:
          HOME: /data
        command: [ '/init-wallet-k8s.sh' ]
        depends_on:
          - bitcoind

    volumes:
      bitcoin_data:
      alice-data:

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Create env file
        run: |
          touch .env
          echo ROOT_KEY=${{ secrets.ROOT_KEY }} >> .env
          cat .env

      - name: Run tests for LNURL
        run: cargo test --verbose
        env: 
          LN_CLIENT_TYPE: LNURL
          LNURL_ADDRESS: ${{ secrets.LNURL_ADDRESS }}

      - name: Run tests for LND
        run: cargo test --verbose
        env:
          LN_CLIENT_TYPE: LND
