name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose -f docker-compose-lnd-test.yml up --build -d

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Create env file
        run: |
          touch .env
          echo ROOT_KEY=${{ secrets.ROOT_KEY }} >> .env
          cat .env

      - name: Run tests for LNURL
        run: cargo test --verbose
        env: 
          LN_CLIENT_TYPE: LNURL
          LNURL_ADDRESS: ${{ secrets.LNURL_ADDRESS }}

      - name: Extract Macaroon and Cert Hex
        run: |
          export MACAROON_HEX=$(docker exec lndnode xxd -p /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon | tr -d '\n')
          export CERT_HEX=$(docker exec lndnode xxd -p /root/.lnd/tls.cert | tr -d '\n')
          
          echo "MACAROON_HEX=$MACAROON_HEX" >> $GITHUB_ENV
          echo "CERT_HEX=$CERT_HEX" >> $GITHUB_ENV

      - name: Run tests for LND
        run: cargo test --verbose
        env:
          LN_CLIENT_TYPE: LND
          LND_ADDRESS: lsat-middleware-rust-bitcoind-1:10009
          MACAROON_HEX: ${{ env.MACAROON_HEX }}
          CERT_HEX: ${{ env.CERT_HEX }}
